plugin.id=plugin_example
plugin.main-class=mc.plugin.example.examplePlugin
plugin.version=1.0.0.003
plugin.date=2025-10-29--2025-11-03
plugin.description=Плагін-приклад

db.count=2
db.1.name=msgbase_dev_view
db.1.type=postgres
db.1.url=jdbc:postgresql://localhost:5432/msgbase
db.1.username=msgbase_msg_view
db.1.password=msgbase_msg_view
db.1.connectByPlugin=0
db.2.name=kbase_test
db.2.type=postgres
db.2.url=jdbc:postgresql://localhost:5432/kbase_test
db.2.username=
db.2.password=
db.2.connectByPlugin=1